name: Build and Validate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate package.json
      run: npm run start --dry-run || echo "No start script defined"
    
    - name: Check server file exists
      run: |
        if [ -f "server.mjs" ]; then
          echo "✅ server.mjs exists"
          node -c server.mjs
          echo "✅ server.mjs syntax is valid"
        else
          echo "❌ server.mjs not found"
          exit 1
        fi
    
    - name: Test package installation
      run: |
        npm pack
        npm install -g ./mcp-postgres-*.tgz
        echo "✅ Package installed successfully"